name: Deploy

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: environment
        default: 'prod-1'
        options:
          - 'dev-1'
          - 'prod-1'
      chart-branch:
        description: 'Branch to checkout the chart from'
        required: true
        type: string
        default: 'main'

jobs:
  build:
    name: Build All
    permissions: write-all
    uses: ./.github/workflows/docker.yml
    secrets: inherit

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [ build ]
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Shorten hash
        id: shorten_hash
        run: |
          if ${{ github.event_name == 'workflow_run' }} && ${{ github.event.workflow_run.conclusion == 'success' }}; then
            echo "HASH=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          else
            echo "HASH=$(git describe --tags)" >> $GITHUB_ENV
          fi

      - name: Import secrets
        id: import-secrets
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: userpass
          username: ${{ secrets.VAULT_USER }}
          password: ${{ secrets.VAULT_PASS }}
          secrets: |
            ${{ secrets.VAULT_MOUNT }}/data/${{ secrets.VAULT_GITHUB_API_NAME }} ${{ secrets.VAULT_GITHUB_API_KEY }} | GITHUB_TOKEN ;
            ${{ secrets.VAULT_MOUNT }}/data/${{ secrets.VAULT_KUBE_CONFIG_NAME }} ${{ secrets.VAULT_KUBE_CONFIG_KEY }} | KUBE_CONFIG ;

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.chart-branch }}
          repository: Jacobbrewer1/supporting-charts
          path: ./charts
          token: ${{ steps.import-secrets.outputs.GITHUB_TOKEN }}

      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: helm upgrade --install dba-website ./charts --values charts/valueFiles/${{ inputs.environment }}/dba-website.yaml --set image.tag=${{ steps.shorten_hash.outputs.sha_short_deploy }}
          kubeconfig: '${{ steps.import-secrets.outputs.KUBE_CONFIG }}'
